# Nginx.
FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf
COPY upstream.conf /etc/nginx/upstream.conf
COPY default.conf /etc/nginx/conf.d/default.conf
